"""add task formats and examples

Revision ID: 154a09fc8b90
Revises: 20a76f6bfbbd
Create Date: 2026-04-14 01:55:42.386901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154a09fc8b90'
down_revision: Union[str, Sequence[str], None] = '20a76f6bfbbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('input_format', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('output_format', sa.Text(), nullable=True))
    op.add_column('task', sa.Column('examples', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'examples')
    op.drop_column('task', 'output_format')
    op.drop_column('task', 'input_format')
    # ### end Alembic commands ###
