"""change duration to integer minutes

Revision ID: 4bc29189a46a
Revises: 970c436f43d3
Create Date: 2026-04-25 20:49:58.029218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bc29189a46a'
down_revision: Union[str, Sequence[str], None] = '970c436f43d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("DROP VIEW IF EXISTS upcoming_and_active_contests")
    op.execute("DROP VIEW IF EXISTS contest_statistics")
    op.alter_column(
        "contest",
        "duration",
        type_=sa.Integer(),
        postgresql_using="EXTRACT(EPOCH FROM duration) / 60"
    )
    
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contest",
        "duration",
        type_=postgresql.INTERVAL,
        postgresql_using="duration * interval '1 minute'"
    )
    op.execute("DROP VIEW IF EXISTS upcoming_and_active_contests")
