"""change task status default

Revision ID: 4ff3cdc93c91
Revises: 4bc29189a46a
Create Date: 2026-04-28 20:29:40.199866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff3cdc93c91'
down_revision: Union[str, Sequence[str], None] = '4bc29189a46a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.execute("""
        UPDATE task
        SET status = 'READY'
        WHERE status IS NULL
    """)
    op.alter_column(
        "task",
        "status",
        existing_type=sa.String(),
        nullable=False,
        server_default="DRAFT"
    )
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
