"""add many sandboxes per one solution

Revision ID: 5e5918ce4ac4
Revises: 154a09fc8b90
Create Date: 2026-04-19 21:44:57.927290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e5918ce4ac4'
down_revision: Union[str, Sequence[str], None] = '154a09fc8b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS sandbox_results_with_details")
    op.add_column('sandbox', sa.Column('execution_time_ms', sa.Integer(), nullable=True))
    op.add_column('sandbox', sa.Column('memory_used_kb', sa.Integer(), nullable=True))
    op.add_column('sandbox', sa.Column('test_number', sa.Integer(), nullable=True))
    op.add_column('sandbox', sa.Column('error_output', sa.Text(), nullable=True))
    op.execute("UPDATE sandbox SET execution_time_ms = 0 WHERE execution_time_ms IS NULL")
    op.execute("UPDATE sandbox SET test_number = 1 WHERE test_number IS NULL")
    op.drop_constraint(op.f('uq_sandbox_solution'), 'sandbox', type_='unique')
    op.drop_index(op.f('ix_sandbox_sandbox_sol'), table_name='sandbox')
    op.create_index(op.f('ix_sandbox_sandbox_sol'), 'sandbox', ['sandbox_sol'], unique=False)
    op.drop_column('sandbox', 'execution_time')
    op.drop_column('sandbox', 'memory_used')
    op.alter_column('sandbox', 'execution_time_ms', nullable=False)
    op.alter_column('sandbox', 'test_number', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sandbox', sa.Column('memory_used', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('sandbox', sa.Column('execution_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_sandbox_sandbox_sol'), table_name='sandbox')
    op.create_index(op.f('ix_sandbox_sandbox_sol'), 'sandbox', ['sandbox_sol'], unique=True)
    op.create_unique_constraint(op.f('uq_sandbox_solution'), 'sandbox', ['sandbox_sol'], postgresql_nulls_not_distinct=False)
    op.drop_column('sandbox', 'error_output')
    op.drop_column('sandbox', 'test_number')
    op.drop_column('sandbox', 'memory_used_kb')
    op.drop_column('sandbox', 'execution_time_ms')
    # ### end Alembic commands ###
