"""added points to task

Revision ID: 809f83b210bb
Revises: 4ff3cdc93c91
Create Date: 2026-05-05 22:19:19.064078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '809f83b210bb'
down_revision: Union[str, Sequence[str], None] = '4ff3cdc93c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('points', sa.Integer(), nullable=True))
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'DRAFT'::character varying"),
               nullable=False)
    op.drop_column('task', 'points')
    # ### end Alembic commands ###
